apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    app: locust-worker
spec:
  replicas: 1 # Adjust this as needed
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: ojoxdan/locust-ptest # Ensure this is your correct Docker image
          resources:
            requests:
              cpu: 3 # Request 0.5 CPU cores
              memory: "4Gi" # Request 256 MiB of memory
            limits:
              cpu: 4 # Limit to 1 CPU core
              memory: "8Gi" # Limit to 512 MiB of memory
          env:
            - name: LOCUST_MASTER_NODE_HOST
              value: locust-master-service # This should be the name of your master service
            - name: LOCUST_HOST
              value: "http://5.161.161.219:9000" # Update this to your target URL
