apiVersion: v1
kind: Service
metadata:
  annotations:
    load-balancer.hetzner.cloud/ipv6-disabled: "true"
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/name: lbtest
  name: locust-master-service
spec:
  type: LoadBalancer
  selector:
    app: locust-master
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: web
    - port: 5557
      targetPort: 5557
      protocol: TCP
      name: master-port-1
    - port: 5558
      targetPort: 5558
      protocol: TCP
      name: master-port-2
