apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: ojoxdan/locust-ptest
          ports:
            - containerPort: 8089
            - containerPort: 5557
            - containerPort: 5558
          env:
            - name: LOCUST_HOST
              value: "http://google.com"
              # value: "http://5.161.161.219:9000"
