apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-inventory-worker
  labels:
    name: locust-inventory-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-inventory-worker
  template:
    metadata:
      labels:
        app: locust-inventory-worker
        name: locust-inventory-worker
        role: worker
    spec:
      containers:
        - name: locust-inventory-worker
          image: ojoxdan/locust-ptest # Locust version
          resources:
            limits:
              cpu: 2
            requests:
              cpu: 2
          env:
            - name: LOCUST_MODE_WORKER
              value: "true"
            - name: LOCUST_MASTER_NODE_HOST
              value: locust-inventory-master # Master Deployment Name
            - name: LOCUST_LOCUSTFILE
              value: locustfile.py
              # value: load_tests/inventory/locustfile.py
            - name: LOCUST_HOST
              value: "http://5.161.161.219:9000"
              # value: "http://0.0.0.0:8009"
